source: site
paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: collections
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  data:
    path: _data
    output: false
    icon:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: collections/_posts
    output: true
    icon:
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  pages:
    path: collections/_pages
    output: true
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.html
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  projects:
    path: collections/_projects
    output: true
    description: ''
    icon: work_outline
    preview:
      text:
      subtext:
        - key: subtitle
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  testimonials:
    path: collections/_testimonials
    output: false
    description: ''
    icon: format_quote
    preview:
      text:
      subtext:
        - key: position
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: descin
    _editables:
    _enabled_editors:
      - data
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/testimonial.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
  drafts:
    path: collections/_drafts
    output: true
    icon:
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  gallery:
    path: collections/photo_gallery
    output: true
    description: ''
    icon: photo
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/gallery.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
      - gallery
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data
_inputs:
  gradient_stop:
    type: color
    options:
      format: hex
      alpha: true
      empty_type:
    label: Color
    cascade: true
  tags:
    type: multiselect
    options:
      format: rgb
      alpha: true
      allow_create: true
      empty_type: array
    cascade: true
_structures:
  content_blocks:
    style: modal
data_config: true
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: US/Eastern
markdown:
  engine:
  options:
